"use strict";
const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const root=__dirname,dataPath=process.env.DATA_PATH||path.join(process.env.RAILWAY_VOLUME_MOUNT_PATH||"/tmp","sentinel-users.json"),sessions=new Map(),rate=new Map();
const adminHash="a988aa71c14d6636b5d10bd345f76f22c36ceaa18d99586cb8f6a644681d5bcdb89810d8cef29f3c23f2274ec01397fc1fca265f5762e3197b874099176e89af";
const hash=(password,salt)=>crypto.scryptSync(password,salt,64).toString("hex"),safe=(a,b)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&crypto.timingSafeEqual(x,y)};
function seed(){return {users:[{id:"USR-ADMIN-001",username:"Fiifi",name:"Fiifi",role:"ADMIN",status:"ACTIVE",salt:"sentinel-admin-v1",passwordHash:adminHash,createdAt:new Date().toISOString(),approvedAt:new Date().toISOString()}],audit:[]}}
function load(){try{return JSON.parse(fs.readFileSync(dataPath,"utf8"))}catch{return seed()}}function save(d){fs.mkdirSync(path.dirname(dataPath),{recursive:true});fs.writeFileSync(dataPath,JSON.stringify(d,null,2),{mode:0o600})}function event(d,actor,action,target){d.audit.unshift({id:crypto.randomUUID(),actor,action,target,timestamp:new Date().toISOString()});d.audit.splice(300)}
const headers={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"no-referrer","Content-Security-Policy":"default-src 'self'; style-src 'self'; base-uri 'none'"};const send=(r,s,b)=>{r.writeHead(s,headers);r.end(JSON.stringify(b))};const body=req=>new Promise((ok,bad)=>{let x="";req.on("data",c=>{x+=c;if(x.length>10000)bad(Error("Request too large"))});req.on("end",()=>{try{ok(JSON.parse(x||"{}"))}catch{bad(Error("Invalid request"))}})});
const current=req=>sessions.get((req.headers.authorization||"").replace("Bearer ",""));function auth(req,res,admin=false){const u=current(req);if(!u||u.status!=="ACTIVE"||(admin&&u.role!=="ADMIN")){send(res,403,{error:"Permission denied."});return null}return u}
function validateUser(username,password){return /^[A-Za-z0-9_.-]{3,32}$/.test(username)&&typeof password==="string"&&password.length>=8&&password.length<=128}
function staticFile(url,res){const name=url==="/"?"index.html":decodeURIComponent(url).replace(/^\//,"");if(!/^[\w.-]+$/.test(name))return send(res,404,{error:"Not found"});const file=path.join(root,name),types={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8"};if(!types[path.extname(file)]||!fs.existsSync(file)){res.writeHead(404,{"Content-Type":"text/plain"});return res.end("Not found")}res.writeHead(200,{...headers,"Content-Type":types[path.extname(file)]});fs.createReadStream(file).pipe(res)}
async function handle(req,res){try{const url=new URL(req.url,"http://localhost"),ip=req.socket.remoteAddress||"local",times=(rate.get(ip)||[]).filter(t=>Date.now()-t<60000);if(times.length>90)return send(res,429,{error:"Too many requests. Try again shortly."});times.push(Date.now());rate.set(ip,times);const d=load();if(req.method==="POST"&&url.pathname==="/api/register"){const b=await body(req),username=String(b.username||"").trim(),password=b.password||"";if(!validateUser(username,password))return send(res,400,{error:"Use a 3-32 character username and password of at least 8 characters."});if(d.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))return send(res,409,{error:"That username is already registered."});const salt=crypto.randomBytes(16).toString("hex"),u={id:`USR-${crypto.randomUUID().slice(0,8)}`,username,name:String(b.name||username).trim().slice(0,80),role:"USER",status:"PENDING",salt,passwordHash:hash(password,salt),createdAt:new Date().toISOString()};d.users.push(u);event(d,username,"ACCESS_REQUESTED",username);save(d);return send(res,201,{message:"Access request submitted. An administrator must approve it before you can sign in."})}if(req.method==="POST"&&url.pathname==="/api/login"){const b=await body(req),u=d.users.find(x=>x.username.toLowerCase()===String(b.username||"").toLowerCase());if(!u||!safe(hash(String(b.password||""),u.salt),u.passwordHash))return send(res,401,{error:"Incorrect username or password."});if(u.status!=="ACTIVE")return send(res,403,{error:"Your account is pending administrator approval."});const token=crypto.randomUUID();sessions.set(token,u);event(d,u.username,"SIGNED_IN",u.username);save(d);return send(res,200,{token,user:{id:u.id,username:u.username,name:u.name,role:u.role}})}if(!url.pathname.startsWith("/api/"))return staticFile(url.pathname,res);if(req.method==="POST"&&url.pathname==="/api/logout"){sessions.delete((req.headers.authorization||"").replace("Bearer ",""));return send(res,200,{ok:true})}if(req.method==="GET"&&url.pathname==="/api/me"){const u=auth(req,res);if(!u)return;return send(res,200,{user:{id:u.id,username:u.username,name:u.name,role:u.role}})}if(req.method==="GET"&&url.pathname==="/api/admin/users"){const u=auth(req,res,true);if(!u)return;return send(res,200,{users:d.users.map(({passwordHash,salt,...x})=>x),audit:d.audit})}if(req.method==="POST"&&/^\/api\/admin\/users\/[^/]+\/approve$/.test(url.pathname)){const u=auth(req,res,true);if(!u)return;const target=d.users.find(x=>x.id===decodeURIComponent(url.pathname.split("/")[4]));if(!target)return send(res,404,{error:"User not found."});target.status="ACTIVE";target.approvedAt=new Date().toISOString();target.approvedBy=u.username;event(d,u.username,"ACCESS_GRANTED",target.username);save(d);return send(res,200,{message:`Access granted to ${target.username}.`})}return send(res,404,{error:"API route not found."})}catch(e){send(res,400,{error:e.message||"Request failed"})}}
const server=()=>http.createServer(handle);if(require.main===module)server().listen(process.env.PORT||3000,"0.0.0.0",()=>console.log("Sentinel Access running"));module.exports={server,handle};
